"""Trust signal report generator.

Produces two artefacts:
1. TRACK_RECORD.md (repo root) — public summary suitable for GitHub.
   Contains: methodology, backtest KPIs, live rec stats, data reliability.
   No PII, no individual trade detail.

2. .claude/context/track_record_full.jsonl (gitignored) — raw evidence.
   Contains: every scored recommendation with ticker + return.

Call generate_report() to refresh both. Designed to be called
once per week via scheduler or manually via MCP tool.
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path

from app.services import skill_backtest as skill_bt_svc
from app.services import paper_trade as pt_svc
from app.services import data_cache as cache_svc

_ROOT = Path(__file__).resolve().parents[3]
_CTX = _ROOT / ".claude" / "context"
_PUBLIC_OUT = _ROOT / "TRACK_RECORD.md"
_PRIVATE_OUT = _CTX / "track_record_full.jsonl"


def generate_report() -> dict:
    """Build TRACK_RECORD.md and private detail jsonl. Return summary."""
    ts = time.time()
    dt_str = datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # --- Backtest section ---
    bt = skill_bt_svc.latest_results() or {}
    bt_rows: list[dict] = bt.get("results", [])

    # --- Live track record ---
    live = pt_svc.get_track_record(windows=[7, 30, 90])
    live_windows = live.get("windows", {})

    # --- Source reliability ---
    reliability = cache_svc.source_stats_summary(since_s=86400 * 30)

    # --- Write private jsonl ---
    evidence = {
        "generated_at": ts,
        "backtest": bt,
        "live_track_record": live,
        "source_reliability": reliability,
    }
    _CTX.mkdir(parents=True, exist_ok=True)
    with _PRIVATE_OUT.open("w", encoding="utf-8") as f:
        f.write(json.dumps(evidence) + "\n")

    # --- Write public markdown ---
    md = _render_markdown(dt_str, bt_rows, bt, live_windows, reliability)
    _PUBLIC_OUT.write_text(md, encoding="utf-8")

    return {
        "generated_at": ts,
        "public": str(_PUBLIC_OUT),
        "private": str(_PRIVATE_OUT),
        "backtest_skills": len(bt_rows),
        "live_recs_logged": live.get("total_logged", 0),
    }


def _render_markdown(
    dt_str: str,
    bt_rows: list[dict],
    bt_meta: dict,
    live_windows: dict,
    reliability: list[dict],
) -> str:
    lines: list[str] = []
    a = lines.append

    a("# aifolimizer — Track Record & Methodology")
    a("")
    a(f"*Last generated: {dt_str}*  ")
    a("*Auto-generated by `trust_report.generate_report()`. Refresh: `mcp__aifolimizer__generate_trust_report`.*")
    a("")
    a("---")
    a("")
    a("## Disclaimer")
    a("")
    a("> This is a personal DIY investment tool, not financial advice. Past results are")
    a("> not predictive of future performance. The author is not a registered advisor.")
    a("> All figures are self-reported and unaudited by a third party.")
    a("")
    a("---")
    a("")
    a("## Methodology")
    a("")
    a("### Data Sources")
    a("| Source | Type | Tier |")
    a("|---|---|---|")
    a("| yfinance | prices, fundamentals, news | free, no key |")
    a("| FRED | macro (Fed funds, CPI, CAD/USD) | free, no key |")
    a("| CoinGecko v3 | crypto prices | free, no key |")
    a("| CNN Fear & Greed | sentiment | free, no key |")
    a("| Google News RSS | news headlines | free, no key |")
    a("| Finnhub | quotes + fundamentals fallback | free, key required |")
    a("| Alpha Vantage | fundamentals fallback | free, key required |")
    a("| Tiingo | EOD history fallback | free, key required |")
    a("")
    a("### Skills Backtested")
    a("")
    a("Each skill is approximated by a deterministic Python rule applied to OHLC bars.")
    a("LLM thesis, news sentiment, and qualitative overlay are NOT replayed.")
    a("Treat rule-based results as a **lower bound** on actual skill quality.")
    a("")
    if bt_meta:
        a(f"- Universe: {', '.join(bt_meta.get('universe', []))}")
        a(f"- Lookback: {bt_meta.get('lookback_days', 0)} days")
        a(f"- Transaction cost: {bt_meta.get('tx_cost_bps', 0)} bps/leg")
    a("")
    a("---")
    a("")
    a("## Historical Backtest Results")
    a("")
    a("| Skill | Rule Proxy | CAGR % | Sharpe | Sortino | Max DD % | Hit Rate % | Alpha vs SPY % |")
    a("|---|---|---|---|---|---|---|---|")
    for r in bt_rows:
        if "error" in r:
            a(f"| {r['skill']} | — | error | | | | | |")
            continue
        alpha_spy = r.get("alpha_vs_spy_pct")
        a_str = f"{alpha_spy:+.1f}" if alpha_spy is not None else "—"
        a(
            f"| {r['skill']} "
            f"| {r.get('strategy_spec', '')} "
            f"| {r.get('cagr_pct', '')} "
            f"| {r.get('sharpe', '')} "
            f"| {r.get('sortino', '')} "
            f"| {r.get('max_drawdown_pct', '')} "
            f"| {r.get('hit_rate_pct', '')} "
            f"| {a_str} |"
        )
    a("")
    a("*SPY and XEQT.TO returns over same period used as benchmark.*")
    a("")
    a("---")
    a("")
    a("## Forward Paper-Trade (Live)")
    a("")
    a("Every recommendation logged via `log_recommendation` MCP tool.")
    a("Scored daily via `score_recommendations`.")
    a("")
    a("| Window | Count | Win Rate % | Avg Return % |")
    a("|---|---|---|---|")
    for wkey, wdata in live_windows.items():
        count = wdata.get("count", 0)
        wr = wdata.get("win_rate_pct", "—")
        ar = wdata.get("avg_return_pct", "—")
        a(f"| {wkey} | {count} | {wr} | {ar} |")
    a("")
    a("---")
    a("")
    a("## Data Source Reliability (30 days)")
    a("")
    a("| Source | Calls | Success % | Avg Latency ms |")
    a("|---|---|---|---|")
    if reliability:
        for r in reliability:
            a(
                f"| {r['source']} "
                f"| {r['calls']} "
                f"| {r.get('success_rate_pct', '—')} "
                f"| {r.get('avg_latency_ms', '—')} |"
            )
    else:
        a("| *No calls recorded yet* | — | — | — |")
    a("")
    a("---")
    a("")
    a("## Wealthsimple Managed Comparison")
    a("")
    a("Published approximate annualized returns (CA, gross, 2025 disclosure):")
    a("")
    a("| Profile | 1Y % | 3Y % | 5Y % |")
    a("|---|---|---|---|")
    from app.services.alpha_attribution import _WS_MANAGED
    for profile, perf in _WS_MANAGED.items():
        a(f"| {profile} | {perf['1y']} | {perf['3y']} | {perf['5y']} |")
    a("")
    a("*Compare your annualized return from `get_alpha_attribution` to the profile matching your risk level.*")
    a("")
    a("---")
    a("")
    a("## Audit Trail")
    a("")
    a("- Recommendations: `.claude/context/recommendations.jsonl` (gitignored, local)")
    a("- Scored history: `.claude/context/scored_recommendations.jsonl` (gitignored, local)")
    a("- Equity curve: `.claude/context/portfolio_history.jsonl` (gitignored, local)")
    a("- Backtest runs: `backend/.cache/backtests/` (gitignored, local)")
    a("- This file: `TRACK_RECORD.md` — committed to repo, git-timestamped")
    a("")
    a("Git history of this file provides tamper-evident timestamps for each report version.")
    a("")

    return "\n".join(lines)
